# 114 sure: (Türkçe ad, Türkçe anlam)
SURAHS_TR = [
 ("Fâtiha","Açılış"),("Bakara","İnek"),("Âl-i İmrân","İmrân Ailesi"),("Nisâ","Kadınlar"),
 ("Mâide","Sofra"),("En'âm","Davarlar"),("A'râf","Yüksek Yerler"),("Enfâl","Ganimetler"),
 ("Tevbe","Tövbe"),("Yûnus","Yûnus"),("Hûd","Hûd"),("Yûsuf","Yûsuf"),("Ra'd","Gök Gürültüsü"),
 ("İbrâhim","İbrâhim"),("Hicr","Hicr"),("Nahl","Arı"),("İsrâ","Gece Yürüyüşü"),("Kehf","Mağara"),
 ("Meryem","Meryem"),("Tâhâ","Tâhâ"),("Enbiyâ","Peygamberler"),("Hac","Hac"),("Mü'minûn","İnananlar"),
 ("Nûr","Işık"),("Furkân","Ayırt Edici"),("Şuarâ","Şairler"),("Neml","Karınca"),("Kasas","Kıssalar"),
 ("Ankebût","Örümcek"),("Rûm","Romalılar"),("Lokmân","Lokmân"),("Secde","Secde"),("Ahzâb","Topluluklar"),
 ("Sebe'","Sebe'"),("Fâtır","Yaratan"),("Yâsîn","Yâsîn"),("Sâffât","Saf Tutanlar"),("Sâd","Sâd"),
 ("Zümer","Gruplar"),("Gâfir","Bağışlayan"),("Fussilet","Ayrıntılı Kılındı"),("Şûrâ","Danışma"),
 ("Zuhruf","Süs"),("Duhân","Duman"),("Câsiye","Diz Çöken"),("Ahkâf","Kum Tepeleri"),("Muhammed","Muhammed"),
 ("Fetih","Fetih"),("Hucurât","Odalar"),("Kâf","Kâf"),("Zâriyât","Savuranlar"),("Tûr","Dağ"),
 ("Necm","Yıldız"),("Kamer","Ay"),("Rahmân","Rahmân"),("Vâkıa","Olay"),("Hadîd","Demir"),
 ("Mücâdele","Tartışma"),("Haşr","Toplanma"),("Mümtehine","İmtihan Edilen"),("Saf","Saf"),
 ("Cum'a","Cuma"),("Münâfikûn","İkiyüzlüler"),("Teğâbün","Aldanış"),("Talâk","Boşanma"),
 ("Tahrîm","Yasaklama"),("Mülk","Egemenlik"),("Kalem","Kalem"),("Hâkka","Gerçekleşen"),
 ("Meâric","Yükselme Yolları"),("Nûh","Nûh"),("Cin","Cinler"),("Müzzemmil","Örtünen"),
 ("Müddessir","Bürünen"),("Kıyâme","Diriliş"),("İnsân","İnsan"),("Mürselât","Gönderilenler"),
 ("Nebe'","Haber"),("Nâziât","Söküp Çıkaranlar"),("Abese","Yüzünü Ekşitti"),("Tekvîr","Dürülme"),
 ("İnfitâr","Yarılma"),("Mutaffifîn","Ölçüde Hile Yapanlar"),("İnşikâk","Yarılma"),("Bürûc","Burçlar"),
 ("Târık","Gece Gelen"),("A'lâ","En Yüce"),("Gâşiye","Kaplayan"),("Fecr","Şafak"),("Beled","Şehir"),
 ("Şems","Güneş"),("Leyl","Gece"),("Duhâ","Kuşluk"),("İnşirâh","Ferahlık"),("Tîn","İncir"),
 ("Alak","Kan Pıhtısı"),("Kadir","Kadir"),("Beyyine","Apaçık Delil"),("Zilzâl","Sarsıntı"),
 ("Âdiyât","Koşanlar"),("Kâria","Çarpacak Olan"),("Tekâsür","Çoklukla Övünme"),("Asr","İkindi/Zaman"),
 ("Hümeze","Arkadan Çekiştiren"),("Fîl","Fil"),("Kureyş","Kureyş"),("Mâûn","Yardım"),("Kevser","Kevser"),
 ("Kâfirûn","İnkârcılar"),("Nasr","Yardım"),("Tebbet","Kurusun"),("İhlâs","Samimiyet"),
 ("Felak","Şafak"),("Nâs","İnsanlar"),
]
assert len(SURAHS_TR) == 114, len(SURAHS_TR)
